services:
  db:
    image: mysql:8.0
    container_name: lucee-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "3308:3306"

  lucee:
    image: lucee/lucee
    container_name: lucee-app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "1988:8888"
    volumes:
      - ./src:/var/www/

volumes:
  db_data:
