name: Lucee & MySQL CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build and Start Containers
        run: docker compose up -d
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}

      - name: Wait for MySQL to be ready
        run: |
          # Usamos a senha de ROOT para o mysqladmin ping
          until docker exec lucee-mysql-db mysqladmin ping -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" | grep "mysqld is alive"; do
            echo "Aguardando MySQL..."
            sleep 3
          done

      - name: Verify Application Response
        run: |
          curl -f --retry 10 --retry-delay 5 http://localhost:1988/index.cfm || exit 1

      - name: Check Database Content
        run: |
          # Aqui testamos o acesso com o usuário da APLICAÇÃO (luceeapp) 
          # para garantir que as permissões dele estão corretas.
          RESULT=$(docker exec lucee-mysql-db mysql -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASSWORD }}" ${{ secrets.DB_NAME }} -N -e "SELECT COUNT(*) FROM mensagens;")
          
          if [ "$RESULT" -eq 0 ]; then
            echo "Erro: Banco de dados está vazio!"
            exit 1
          fi
          echo "Sucesso: Encontradas $RESULT mensagens no banco."

      - name: Stop Containers
        if: ${{ always() }}
        run: docker compose down -v